config/routes.rb
Rails.application.routes.draw do
  resources :fertilizers
  resources :lands
  resources :customers do
    resources :fertilizers
    resources :lands
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :lands, dependent: :destroy
    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/models/fertilizer.rb
class Fertilizer < ApplicationRecord
end

app/models/land.rb
class Land < ApplicationRecord
  belongs_to :customer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :mobile, :nid, :father_name, :city, :address)
    end
end

app/controllers/fertilizers_controller.rb
class FertilizersController < ApplicationController
  before_action :set_fertilizer, only: [:show, :edit, :update, :destroy]

  # GET /fertilizers
  # GET /fertilizers.json
  def index
    @fertilizers = Fertilizer.all
  end

  # GET /fertilizers/1
  # GET /fertilizers/1.json
  def show
  end

  # GET /fertilizers/new
  def new
    @fertilizer = Fertilizer.new
  end

  # GET /fertilizers/1/edit
  def edit
  end

  # POST /fertilizers
  # POST /fertilizers.json
  def create
    @fertilizer = Fertilizer.new(fertilizer_params)

    respond_to do |format|
      if @fertilizer.save
        format.html { redirect_to @fertilizer, notice: 'Fertilizer was successfully created.' }
        format.json { render :show, status: :created, location: @fertilizer }
      else
        format.html { render :new }
        format.json { render json: @fertilizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fertilizers/1
  # PATCH/PUT /fertilizers/1.json
  def update
    respond_to do |format|
      if @fertilizer.update(fertilizer_params)
        format.html { redirect_to @fertilizer, notice: 'Fertilizer was successfully updated.' }
        format.json { render :show, status: :ok, location: @fertilizer }
      else
        format.html { render :edit }
        format.json { render json: @fertilizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fertilizers/1
  # DELETE /fertilizers/1.json
  def destroy
    @fertilizer.destroy
    respond_to do |format|
      format.html { redirect_to fertilizers_url, notice: 'Fertilizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fertilizer
      @fertilizer = Fertilizer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fertilizer_params
      params.require(:fertilizer).permit(:f_type, :amount, :price, :date)
    end
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  before_action :set_land, only: [:show, :edit, :update, :destroy]

  # GET /lands
  # GET /lands.json
  def index
    @customer = Customer.find(params[:customer_id])
    @lands = @customer.lands
  end

  # GET /lands/1
  # GET /lands/1.json
  def show
    @customer = Customer.find(params[:customer_id])
  end

  # GET /lands/new
  def new
    @land = Land.new
    @customer = Customer.find(params[:customer_id])
  end

  # GET /lands/1/edit
  def edit
    @customer = Customer.find(params[:customer_id])
  end

  # POST /lands
  # POST /lands.json
  def create
    @land = Land.new(land_params)
    @customer = Customer.find(params[:customer_id])
    @land.customer_id = @customer.id
    respond_to do |format|
      if @land.save
        format.html { redirect_to customer_lands_path(@customer,@land), notice: 'Land was successfully created.' }
        format.json { render :show, status: :created, location: @land }
      else
        format.html { render :new }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lands/1
  # PATCH/PUT /lands/1.json
  def update
    @customer = Customer.find(params[:customer_id])
    respond_to do |format|
      if @land.update(land_params)
        format.html { redirect_to customer_lands_path(@customer,@land), notice: 'Land was successfully updated.' }
        format.json { render :show, status: :ok, location: @land }
      else
        format.html { render :edit }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lands/1
  # DELETE /lands/1.json
  def destroy
    @customer = Customer.find(params[:customer_id])
    @land.destroy
    respond_to do |format|
      format.html { redirect_to customer_lands_path(@customer,@land), notice: 'Land was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_land
      @land = Land.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def land_params
      params.require(:land).permit(:land_type, :area, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fertilizers_helper.rb
module FertilizersHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :nid %>
    <%= form.text_field :nid %>
  </div>

  <div class="field">
    <%= form.label :father_name %>
    <%= form.text_field :father_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Nid</th>
      <th>Father name</th>
      <th>City</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.mobile %></td>
        <td><%= customer.nid %></td>
        <td><%= customer.father_name %></td>
        <td><%= customer.city %></td>
        <td><%= customer.address %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @customer.mobile %>
</p>

<p>
  <strong>Nid:</strong>
  <%= @customer.nid %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @customer.father_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/fertilizers/_form.html.erb
<%= form_with(model: fertilizer, local: true) do |form| %>
  <% if fertilizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fertilizer.errors.count, "error") %> prohibited this fertilizer from being saved:</h2>

      <ul>
        <% fertilizer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :f_type %>
    <%= form.number_field :f_type %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fertilizers/edit.html.erb
<h1>Editing Fertilizer</h1>

<%= render 'form', fertilizer: @fertilizer %>

<%= link_to 'Show', @fertilizer %> |
<%= link_to 'Back', fertilizers_path %>

app/views/fertilizers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fertilizers</h1>

<table>
  <thead>
    <tr>
      <th>F type</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fertilizers.each do |fertilizer| %>
      <tr>
        <td><%= fertilizer.f_type %></td>
        <td><%= fertilizer.amount %></td>
        <td><%= fertilizer.price %></td>
        <td><%= fertilizer.date %></td>
        <td><%= link_to 'Show', fertilizer %></td>
        <td><%= link_to 'Edit', edit_fertilizer_path(fertilizer) %></td>
        <td><%= link_to 'Destroy', fertilizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fertilizer', new_fertilizer_path %>

app/views/fertilizers/new.html.erb
<h1>New Fertilizer</h1>

<%= render 'form', fertilizer: @fertilizer %>

<%= link_to 'Back', fertilizers_path %>

app/views/fertilizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F type:</strong>
  <%= @fertilizer.f_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @fertilizer.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fertilizer.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @fertilizer.date %>
</p>

<%= link_to 'Edit', edit_fertilizer_path(@fertilizer) %> |
<%= link_to 'Back', fertilizers_path %>

app/views/lands/_form.html.erb
<%= form_with(model: [@customer, land], local: true) do |form| %>
  <% if land.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(land.errors.count, "error") %> prohibited this land from being saved:</h2>

      <ul>
        <% land.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :land_type %>
    <%= form.number_field :land_type %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.number_field :area %>
  </div>

  <div class="field">
    <%= @customer.full_name() %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lands/edit.html.erb
<h1>Editing Land</h1>

<%= render 'form', land: @land %>

<%= link_to 'Show', @land %> |
<%= link_to 'Back', lands_path %>

app/views/lands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lands</h1>

<table>
  <thead>
    <tr>
      <th>Land type</th>
      <th>Area</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lands.each do |land| %>
      <tr>
        <td><%= land.land_type %></td>
        <td><%= land.area %></td>
        <td><%= land.customer.full_name() %></td>
        <td><%= link_to 'Show', land %></td>
        <td><%= link_to 'Edit', edit_customer_land_path(land.customer, land) %></td>
        <td><%= link_to 'Destroy', [land.customer, land], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Land', new_customer_land_path(@customer) %>

app/views/lands/new.html.erb
<h1>New Land</h1>

<%= render 'form', land: @land %>

<%= link_to 'Back', lands_path %>

app/views/lands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Land type:</strong>
  <%= @land.land_type %>
</p>

<p>
  <strong>Area:</strong>
  <%= @land.area %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @land.customer_id %>
</p>

<%= link_to 'Edit', edit_land_path(@land) %> |
<%= link_to 'Back', lands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>